# Generated by Django 6.1.1 on 2026-09-27 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('mixed_count', models.IntegerField(default=0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('category_counts', models.JSONField(blank=True, default=dict)),
                ('daily_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Batch Analysis Record',
                'verbose_name_plural': 'Batch Analysis Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='category',
            field=models.CharField(db_index=True, default='general', help_text='Product or service sector category (e.g. food_dining, ecommerce_retail)', max_length=64),
        ),
        migrations.AddIndex(
            model_name='analysishistory',
            index=models.Index(fields=['user', 'category'], name='analyzer_an_user_id_faeabc_idx'),
        ),
        migrations.AddField(
            model_name='batchanalysisrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='batchanalysisrecord',
            index=models.Index(fields=['user', '-created_at'], name='analyzer_ba_user_id_67251a_idx'),
        ),
    ]
